### ISSUE TITLE
software Readme missing EAP.

### ISSUE THREAD

**Issue by eschabell** [jbossdemocentral/dv-gettingstarted#3]
Readme in software/\* states only installer dv needed but EAP installer needed and update of DV installer to version 6.2:

$ cat README.md 
## Software

Download the following from the Red Hat Customer Portal (http://access.redhat.com)
- JBoss Data Virtualization 6.1.0 (jboss-dv-installer-6.1.0.redhat-3.jar)

and copy to this directory for the init.sh script to work.

Ensure that this file is executable by running:

```
$ chmod +x <path-to-project>/software/jboss-dv-installer-6.1.0.redhat-3.jar
```

$ ls -1

README.md
jboss-dv-installer-6.2.0.redhat-2.jar
jboss-eap-6.4.0-installer.jar

**Comment by kpeeples** [comment]
it actually requires the EAP 6.4.3 rollup patch as well.

**Comment by kpeeples** [comment]
Modified the software/readme to include the 3 required files.
