### ISSUE TITLE
Main readme option 2 update needed.

### ISSUE THREAD

**Issue by eschabell** [jbossdemocentral/dv-gettingstarted#4]
Readme states need installer dv, but not EAP installer... very confusing in this option 2 section:

OPTION 2 - STEPS TO RUN WITHOUT JBDS:
STEP 1: Clone the Repository and Download Data Virtualization
-git clone https://github.com/jbossdemocentral/dv-gettingstarted.git
-Download from jboss.org http://www.jboss.org/products/datavirt/download/
-You must download and install EAP 6.4 and the EAP 6.4.3 as well.
Put the Data Virutalization Download, jboss-dv-installer-6.1.0.redhat-3.jar, into the software folder

**Comment by kpeeples** [comment]
It indicates EAP installer and roll up patch but I will change to clarify.  thanks.

**Comment by kpeeples** [comment]
Hopefully made it clearer that 3 software downloads are required for DV 6.2.
